name: Lowlighter Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: Asia/Manila
         # Language plugin
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: firstname lastname, username, username@users.noreply.github.com
         # IsoCalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
         # Stars plugin
          plugin_stars: yes
         # habits plugin
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
         # followup plugin
          plugin_followup: yes
          plugin_followup_indepth: yes
         # people plugin
          plugin_people: yes
         # activity plugin
          plugin_activity: yes
         # achievements plugin
          plugin_achievements: yes
         # notable contributions plugin
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_repositories: yes
         # Lines plugin
          plugin_lines: yes
         # Stackoverflow plugin
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 14199991
          plugin_stackoverflow_sections: answers-top, answers-recent
          
          
          
          
          
          
          
         
