name: Lowlighter Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - name: General
      #   uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     filename: assets/metrics.svg
      #     config_timezone: Asia/Manila
      #     base: header, activity, community, repositories, metadata
      #     base_indepth: yes,
      #     repositories_affiliations: owner, collaborator, organization_member
      #     # Language plugin
      #     plugin_languages: yes
      #     plugin_languages_indepth: yes
      #     commits_authoring: firstname lastname, username, username@users.noreply.github.com
      #     # IsoCalendar plugin
      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: full-year
      #     # Stars plugin
      #     plugin_stars: yes
      #     # habits plugin
      #     plugin_habits: yes
      #     plugin_habits_from: 1000
      #     plugin_habits_days: 30
      #     plugin_habits_facts: yes
      #     plugin_habits_charts: yes
      #     plugin_habits_charts_type: chartist
      #     plugin_habits_trim: yes
      #     # followup plugin
      #     plugin_followup: yes
      #     plugin_followup_indepth: yes
      #     # people plugin
      #     plugin_people: yes
      #     # activity plugin
      #     plugin_activity: yes
      #     # achievements plugin
      #     plugin_achievements: yes
      #     # notable contributions plugin
      #     plugin_notable: yes
      #     plugin_notable_indepth: yes
      #     plugin_notable_types: commit, pull_request, issue
      #     plugin_notable_repositories: yes
      #     # Lines plugin
      #     plugin_lines: yes
      #     # Stackoverflow plugin
      #     plugin_stackoverflow: yes
      #     plugin_stackoverflow_user: 14199991
      #     plugin_stackoverflow_sections: answers-top, answers-recent
      #     # posts plugin
      #     plugin_posts: yes
      #     plugin_posts_source: dev.to
      #     plugin_posts_descriptions: yes
      #     plugin_posts_covers: yes
      #     plugin_posts_limit: 30
      #     plugin_posts_user: pacholoamit
      #     # wakatime plugin
      #     plugin_wakatime: yes
      #     plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
      #     plugin_wakatime_days: 30
      #     plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
      #     plugin_wakatime_limit: 0

      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: assets/metrics-1.svg
          config_timezone: Asia/Manila
          base: header, activity, community, repositories, metadata
          base_indepth: yes,
          config_display: columns
          repositories_affiliations: owner, collaborator, organization_member
          # Language plugin
          plugin_languages: yes
          plugin_languages_indepth: yes
          # Wakatime plugin
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_limit: 0
          # Habits plugin
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
          # Stars plugin
          plugin_stars: yes
          # IsoCalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Lines plugin
          plugin_lines: yes
          # People plugin
          plugin_people: yes
          # Followup plugin
          plugin_followup: yes
          plugin_followup_indepth: yes

      - name: Metrics 2 markdown
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: assets/metrics-2.md
          config_timezone: Asia/Manila
          config_output: markdown
          base: ""
          # Posts plugin
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_limit: 30
          plugin_posts_user: pacholoamit
          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          # Notable contributions plugin
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_repositories: yes
          # Stackoverflow plugin
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 14199991
          plugin_stackoverflow_sections: answers-top, answers-recent

      # - name: Wakatime Plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/wakatime.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_wakatime: yes
      #     plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
      #     plugin_wakatime_days: 30
      #     plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
      #     plugin_wakatime_limit: 0

      # - name: Posts plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/posts.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_posts: yes
      #     plugin_posts_source: dev.to
      #     plugin_posts_descriptions: yes
      #     plugin_posts_covers: yes
      #     plugin_posts_limit: 30
      #     plugin_posts_user: pacholoamit

      # - name: Stackoverflow plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/stackoverflow.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_stackoverflow: yes
      #     plugin_stackoverflow_user: 14199991
      #     plugin_stackoverflow_sections: answers-top, answers-recent

      # - name: Lines plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/lines.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_lines: yes

      # - name: Notable contributions plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/notable.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_notable: yes
      #     plugin_notable_indepth: yes
      #     plugin_notable_types: commit, pull_request, issue
      #     plugin_notable_repositories: yes

      # - name: Achievements plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/achievements.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_achievements: yes

      # - name: People plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/people.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_people: yes

      # - name: Followup plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/followup.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_followup: yes
      #     plugin_followup_indepth: yes

      # - name: Habits plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/habits.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_habits: yes
      #     plugin_habits_from: 1000
      #     plugin_habits_days: 30
      #     plugin_habits_facts: yes
      #     plugin_habits_charts: yes
      #     plugin_habits_charts_type: chartist
      #     plugin_habits_trim: yes

      # - name: Stars plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/stars.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_stars: yes

      # - name: IsoCalendar plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/isocalendar.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: full-year

      # - name: Languages plugin
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/languages.svg
      #     config_timezone: Asia/Manila
      #     token: ${{ secrets.GH_TOKEN }}
      #     base: ""
      #     plugin_languages: yes
      #     plugin_languages_indepth: yes
