name: Lowlighter Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: Asia/Manila
#         Language plugin
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: firstname lastname, username, username@users.noreply.github.com
#         IsoCalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
